#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xdefaults &
setxkbmap -option "ctrl:nocaps" &

# Start the system tray
stalonetray -i 4 --window-type normal --window-strut none --background black --icon-gravity NE &

if [ -x /usr/bin/xfce4-volumed ] ; then
    /usr/bin/xfce4-volumed &
fi
if [ -x /usr/bin/nm-applet ] ; then
    /usr/bin/nm-applet --sm-disable &
fi
if [ -x /usr/bin/xfce4-clipman ] ; then
    /usr/bin/xfce4-clipman &
fi


exec xmonad
